### ISSUE TITLE
Syntax error after loading module

### ISSUE THREAD

**Issue by stardothosting** [mattvb91/caddy-php#14]
Just loaded up the module and attempted to use only to discover this fatal error 

```
>>> use mattvb91\CaddyPhp\Caddy;
>>> $caddy = new Caddy();
PHP Error:  syntax error, unexpected 'static' (T_STATIC) in /home/<redacted>/vendor/mattvb91/caddy-php/src/Caddy.php on line 166
```

Any idea why that would happen?

**Comment by mattvb91** [comment]
I think this may be to do with php versions. (I just noticed I havent locked it to php 8^ in the composer file). Im assuming your on a lower php version?

**Comment by stardothosting** [comment]
php 7.4, yes

**Comment by mattvb91** [comment]
ah yea sorry ill put in a version lock to make it more obvious.

If you want / use docker you can use the https://github.com/mattvb91/caddy-php/blob/develop/docker-compose.yml file and just use that for playing around on. It mounts the repository directory into `/app` and you should be good to go for playing around with on php 8

**Comment by stardothosting** [comment]
No worries, this is a good enough reason to upgrade my framework & PHP version anyways. Thank you for clarifying!
